name: nicklas bergman
favicon: null
layout_spectrum: 0.09680159855633974
typography_spectrum: 0.7002357519231737
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.25357373361475766
  lightness: 0.6900259545072913
  saturation: 0.7641398266423494
  rhythmicContrast: 0.13328130985610187
purpose: []
